### ISSUE TITLE
Is there any reason that the FileSystemCache doesn't compare filemtimes?

### ISSUE THREAD

**Issue by mikesherov** [bobthecow/mustache.php#261]
Thanks again for all your hard work, Justin. We're looking at using the cache option to cache templates on our production site. The issue we're encountering is a cache invalidation strategy. Our current solution is to prepend the cache directory name with a monotonically increasing number that is updated on each deploy. There are drawbacks to this strategy:

1. Cache invalidation is all or nothing, every deploy.
2. This leaves behind directories full of stale cached templates that would need to be clean up by, let's say, cron.

A saner strategy would be to implement filemtime comparison as part of the check to see if a cached template is valid. Is there any reason to *not* do this? If not, I can send a patch that either adds this behavior to the current FileSystemCache or provide it as a new Cache class (just let me know what to call it).

**Comment by bobthecow** [comment]
Because it's faster not to? FileSystemCache uses hash-based cache keys, which automatically "expire" when any of the templates or rendering options change (kind of like [the Rails key-based caching best practice](https://signalvnoise.com/posts/3113-how-key-based-cache-expiration-works)). So it shouldn't ever _need_ invalidated, and it doesn't matter what the mtime is. With a strategy like this, the fastest option is to never explicitly invalidate anything.

**Comment by mikesherov** [comment]
Woah, is that true? Thanks for the info! Sorry for bothering you.

**Comment by bobthecow** [comment]
Oh, no problem at all.
