### ISSUE TITLE
Cache details

### ISSUE THREAD

**Issue by robehickman** [bobthecow/mustache.php#281]
I'm looking for some details on how the template compilation/cache layer is implemented, with reference to the statement on caching lambdas: "This is generally not recommended, as lambda sections are often too dynamic to benefit from caching."

If you have a template which uses lambdas, does the compilation stage execute the lambda, meaning that every different data output would be cached separately. Or does it run the lambda when the compiled template is executed. If the latter I don't see how 'too dynamic to benefit' would come into play.

**Comment by bobthecow** [comment]
It's not the lambda which is the issue, it's the return value of the lambda. The return value of a lambda _is itself_ a template, [which is parsed and compiled by Mustache](https://github.com/mustache/spec/blob/master/specs/%7Elambdas.yml#L29-L42).

Mustache.php _does_ make some optimizations, such as [not actually parsing or compiling a lambda return value when it doesn't contain mustache delimiters](https://github.com/bobthecow/mustache.php/blob/master/src/Mustache/Compiler.php#L332-L338). But in the worst case scenario — say something like `return rand() . '{{ foo }}';` — each return value from a given lambda could result in a different template. With lambda template caching enabled, this would eventually fill your disk with cached templates you're never going to be able to use :)

So, if you have lambdas which really just reuse a couple of static template strings, turn on lambda template caching. Otherwise, leave it off.

Honestly, for templates the size of what (most) lambda sections return, it doesn't make a difference either way.

**Comment by robehickman** [comment]
Thanks for explaining, that makes sense. I wasn't aware they where returning a value which could itself be a template.

**Comment by bobthecow** [comment]
No problem!
