### ISSUE TITLE
is i18n example outdated?

### ISSUE THREAD

**Issue by MiquelAdell** [bobthecow/mustache.php#291]
Hi,

I'm trying to get translations directly into mustache templates.

I'm using this example:
https://github.com/bobthecow/mustache.php/blob/master/test/fixtures/examples/i18n/I18n.php

Im at '2.10.0' btw.

But either I'm not understanding it (I'm not sure what to put on the php that renders the template) or the example is out of date.

First thing I do is create a class that inherits from Mustache_Engine:

    <?php
    
    class Mustache_Engine_I18n extends Mustache_Engine {
        // Variable to be interpolated
        public $name = 'Bob';

        // Add a {{#__}} lambda for i18n
        public $__ = array(__CLASS__, '__trans');

        // A *very* small i18n dictionary :)
        private static $dictionary = array(
            'Hello.'                 => 'Hola.',
            'My name is {{ name }}.' => 'Me llamo {{ name }}.',
        );

        public static function __trans($text)
        {
            return isset(self::$dictionary[$text]) ? self::$dictionary[$text] : $text;
        }
    }

This is the first place where I doubt. Right now the example class doesn't extend no one but [this "old" one](https://github.com/bobthecow/mustache.php/blob/f77cf3729de0e46d6187da2353a4ab438657b6fe/examples/i18n/I18n.php) did extend mustache (not mustache engine).

I have a moustache template like the example:

    test1
    {{#__}}Hello.{{/__}} {{#__}}My name is {{ name }}.{{/__}}
    test2

And in the php that should render everything I have the following:

    …
    $mustache_Engine = new Mustache_Engine_I18n;
    return $mustache_Engine->render($template, $context);
    …

But in the html I get:

	test1

	test2

So I assume I'm missing something important.

Thanks a lot!

**Comment by bobthecow** [comment]
Those examples are run as part of the test suite on every commit, on every push, on every release. The current examples are current, and the (over four year old) outdated examples are outdated ;)

Mustache v1.x used to support extending Mustache itself to add values to the rendering context. Because there was only a single class, this was more like extending a Mustache _Template_ than extending the Engine :)

In v2.x, instead of extending Mustache, you create a View class or an array and render using that.

The thing you're missing is [the code used to wire up those examples during testing](https://github.com/bobthecow/mustache.php/blob/master/test/Mustache/Test/Functional/ExamplesTest.php). In your case, it'd look something like this:

```php
$mustache = new Mustache_Engine();
$context = new I18n();
return $mustache->render($template, $context);
```

Now you'll notice that the I18n class isn't super reusable… It has a `$name` value, which means it's the rendering context for a single template, not a generic helper for translating your entire app. For some better examples, see #69. That issue thread has several examples using generic helper classes or anonymous functions for translating in more real-life sort of situations.

**Comment by MiquelAdell** [comment]
Thanks!

yes, that was what I was missing.

Also another reason to, some day, finally tackle unit testing: understanding unit tests on other projects.

I guess I'll need to understand the example you linked. I guess that starting from [here](https://github.com/bobthecow/mustache.php/issues/69#issuecomment-17439215) it looks promising. 
 
Thanks again, I'm closing this one.

**Comment by bobthecow** [comment]
Yep. That's a good starting point.
