### ISSUE TITLE
helpers?

### ISSUE THREAD

**Issue by thepurpleblob** [bobthecow/mustache.php#303]
Maybe I'm being stupid (!!), but I can't see any documentation for defining custom/new 'helpers'. They are vaguely mentioned in a couple of places but nothing to explain how to create and use them... unless I have missed it.

**Comment by bobthecow** [comment]
To add helpers, you can either either pass them to the initial `Mustache_Engine` constructor call:

```php
$m = new Mustache_Engine([
  'helpers' => $helpers
]);
```

… or set them on the engine with [`setHelpers`](https://github.com/bobthecow/mustache.php/blob/a3f6d55996dd28b58f3a909d474189a3c1aa693f/src/Mustache/Engine.php#L336-L347) before rendering:

```php
$m->setHelpers($helpers);
```

Here, `$helpers` is either an associative array or a `Traversable` with `key => value` mapping a tag name to a primitive, object, closure, etc.

**Comment by thepurpleblob** [comment]
Sorry... I should have been clearer. Possibly I don't understand quite what helpers are. What goes in the array $helpers? I can see how to add them, not how to write one and why I would want to.

**Comment by Svish** [comment]
Example of one helper I'm using:

````PHP
namespace Helper;
class Url
{
	/**
	 * Returns $url prefixed with WEBBASE, or WEBROOT if starting with /.
	 *
	 * - foo => /base/foo
	 * - /foo => http://host/base/foo
	 */
	public function __invoke($url = null, \Mustache_LambdaHelper $render = null)
	{
		if($render)
			$url = $render($url);
		
		return strpos($url, '/') === 0
			? WEBROOT.ltrim($url, '/')
			: WEBBASE.$url;
	}
}
````

How you could add it as a helper:

````PHP
$m->setHelpers([
	'url' => new Helper\Url,
	]);
````

Some examples of how I'm using it in my `layout.mustache`:

````HTML
	<base href="{{#url}}/{{/url}}" />
	<link rel="canonical" href="{{#url}}/{{PATH}}{{/url}}">

	<script>
		var Site = {Url: {Base: '{{url}}', Current: '{{PATH}}'}};
	</script>
````

**Comment by thepurpleblob** [comment]
That's really useful. I would never have guessed though. 

It would be great if this was documented.

**Comment by bobthecow** [comment]
It's documented under [Lambdas](https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#lambdas) in the "Section tags" docs. Specifically, `__invoke` works because of [Mustache's Callable handling](https://github.com/bobthecow/mustache.php/wiki/Callable).

**Comment by thepurpleblob** [comment]
Erm... it isn't (not in the Lambdas section but is in the Callable handling bit).

I wasn't (I'm not sure I am now) clear about the difference/relationship between 'lambdas' and 'helpers'. For people like me who have only ever used mustache.php some of this stuff is a bit confusing. 

I wasn't aware of the __invoke() magic method. Every day an education. 

Thanks again for all the help.

**Comment by thepurpleblob** [comment]
BTW... I was re-reading the docs and noticed you use the term "higher order sections" quite a lot. Can you explain what this means? (I know what a higher order function is)

**Comment by bobthecow** [comment]
Yeah, sorry. That phrase in Mustache.php docs comes directly from the Mustache spec docs. Mustache was born in Ruby-land so it has a lot of Ruby-flavored wording :)

In PHP, calling them "lambda" sections probably makes more sense than "higher order" sections, because they're only _sometimes_ "higher order"…

If your rendering context is an object, a "higher order section" is a section whose value is a higher order function, for example, `shouty` here:

```php
class MyViewModel {
  public function shouty() {
    return function ($text, $render) {
      return strtoupper($render($text));
    }
  }
}
```

But if your rendering context is an associative array, and the value of a key is a closure (or something callable), it counts as "higher order" for the purposes of "higher order sections":

```php
$data = [
  'shouty' => function ($text, $render) {
    return strtoupper($render($text));
  },
];
```

This fun little distinction comes from Ruby, where accessing properties on an object — or values in a map, or indices in an array — is _always_ a function call, so `$data['shouty']` would be a function call which returns a closure, i.e. a higher order function.

**Comment by bobthecow** [comment]
It seems like this issue is answered now? I'm going to go ahead and close it. Feel free to reopen if you have further issues or questions :)
