### ISSUE TITLE
Echoing functions outputting prematurely

### ISSUE THREAD

**Issue by Archer70** [bobthecow/mustache.php#312]
I'm working with an old 'n' busted web app that imposes code practices that aren't the bestest. That is, they have lots of functions that echo their output instead of returning it. This led me to find that anonymous functions are apparently called for their return values (in this case, none) before the template is actually rendered.

Example:

```php
$m = new Mustache_Engine();
echo $m->render('Hello, {{output}}', [
	'output' => function() {
		echo 'test';
	}
]);
```
>testHello,

Is there some fancy way of getting around this? Right now it's looking like my best option is to take the output from that function and save it in a partial, but I'd rather not.

**Comment by bobthecow** [comment]
If you want to see what code is generated by your template, you can pass a cache directory param to `Mustache_Engine` and look at the PHP class it spits out. But what you're seeing is effectively the equivalent of this:

```php
return 'Hello, ' . htmlspecialchars($context['output']());
```

As you might guess, it's impossible to concatenate and return the output of `$context['output']` without calling it. The only way around this would be to call it, but use output buffering to capture the `echo` inside, and concatenate _that_ in the place of the return value.

This raises a few other questions, but they're kind of moot. Mustache won't be doing any output buffering, because, like you said, code practices like this are old and busted, and shouldn't be encouraged :)

But!

You can do it yourself. The easiest way would probably be to make a higher order function to wrap misbehaving functions in:

```php
function buffer($callable) {
    ob_start();
    $ret = call_user_func($callable);
    $buffer = ob_get_clean();

    return $buffer . $ret;
}

$m = new Mustache_Engine();

echo $m->render('Hello, {{ output }}', [
    'output' => buffer(function() { echo 'test'; }),
]);
```

> Hello, test

**Comment by Archer70** [comment]
Oh, that'll do nicely. Thanks!

**Comment by bobthecow** [comment]
No problem!
