### ISSUE TITLE
Not a bug, just a problem I'm having

### ISSUE THREAD

**Issue by MilesHart** [bobthecow/mustache.php#341]
I'm using JSON data as the following:

```
{
            "persons": [{   
                "person": {
                    "name": "Homer",
                    "number": 0
                },
                "person": {
                    "name": "Marge",
                    "number": 1
                }
            }]
         }
```

And my template:

```
<ul>
{{#persons}}
    <li>Name: {{person.name}}</li>
    <li>Number: {{person.number}}</li>
{{/persons}}
</ul>
```

This only seems to render "Marge", any idea why Homer and Marge are not rendering?

**Comment by bobthecow** [comment]
It's your JSON... because you have a single object inside the `persons` array, and it has two keys called `person`, the actual data structure you're getting in PHP (which doesn't allow duplicate keys in the same object) is ...

<img width="762" alt="screen shot 2018-07-15 at 9 36 47 am" src="https://user-images.githubusercontent.com/53660/42735977-9f8f89a4-8812-11e8-94f1-24e375550adb.png">

**Comment by MilesHart** [comment]
Thank you.

**Comment by MilesHart** [comment]
For completeness, here is some working data/template

```
{
            "persons": [
                {"name": "Homer", "number": 0},
                {"name": "Marge", "number": 1}
            ]
         }
```

```
<ul>
{{#persons}}
    <li>Name: {{name}}</li>
    <li>Number: {{number}}</li>
{{/persons}}
</ul>
```
