### ISSUE TITLE
About filters and block pragma compatibility

### ISSUE THREAD

**Issue by camlafit** [bobthecow/mustache.php#390]
Hello

I've tried to enable filters both pragma and block pragma. 
Wiki explains as filters can't be used with partials template but nothing about block compatibility.

I've tried this use case without success : 
**layout.mustache**
```
{{% FILTERS }}
{{% BLOCKS }}
...
```
**home.mustache**
```
{{% BLOCKS }}
{{< layout }}

{{ variable | myfilter }}
```
In this case myfilter is ko.

But if *{{% FILTERS }}* is added in **home.mustache** filters are operational.

Then I don't if : 
* this behavior is normal and act as partial part and in this case maybe to improve documentation
* it's a bug.

Thanks a lot

**Comment by bobthecow** [comment]
The comment in the wiki is saying you can't filter a partial expansion. i.e. _this_ won't work:

```mustache
{{> partial | filter }}
```

… there's nothing preventing filters from being used at the same time as blocks.

I think what you might be missing is that pragma tags don't apply to the entire engine, they apply just to the template that contains them. So because you have `{{% BLOCKS }}` in `home.mustache`, it understands what's going on with the block tag. But if you don't add `{{% FILTERS }}` it interprets your template as "look for a variable in the rendering context called `"variable | myfilter" => ...` which obviously doesn't exist 🙂

Go ahead and use blocks and filters at the same time! In fact, you can enable them when instantiating the engine so you don't need to put them in every template.

**Comment by camlafit** [comment]
Hello

Thanks for your response :) Confirm my misunderstood about difference ```{{% BLOCKS }}``` and ```{{ > partial }}``` there are not.

Maybe to help people as me, a little improve on wiki about ```{{%BLOCKS}}``` and ```{{< layout }}``` repeat could be useful.

And indeed I didn't think to declare it globally directly on instantiating parg, I'll do :)

Thanks a lot
