### ISSUE TITLE
Detecting non-empty list

### ISSUE THREAD

**Issue by tedhenry100** [bobthecow/mustache.php#407]
I only want to include the `<ul>` and `</ul>` tags if the `jobs` is not empty. The following doesn't work. It renders nothing. I tried changing `length` to `size` and `count` with no luck.

```
{{# jobs.length }}
    <ul>
        {{# jobs }}
            <li>{{ title }}</li>
        {{/ jobs }}
    </ul>
{{/ jobs.length }}
```

I can only include the jobs in the data sent to the template if the jobs array is not empty but I can't seem to find a way to detect if the jobs array is present or not.

Do I have to add another property like `jobs_count` to the data in order to achieve what I want?

Thanks!

**Comment by bobthecow** [comment]
Assuming `jobs` is a PHP array, there's no built-in length, size or count property. Something like `{{ jobs.length }}` works in JavaScript or Ruby because both of those languages have a primitive array type with a length property.

In PHP your options are to use an `ArrayObject`, which has a `count` method, or to add another property like `jobs_count` to your rendering data.

You can also use [the FILTERS pragma](https://github.com/bobthecow/mustache.php/wiki/FILTERS-pragma), and specify a helper. Something like…

```php
$m = new \Mustache_Engine([
  'pragmas' => [\Mustache_Engine::PRAGMA_FILTERS]
]);

$m->addHelper('empty', function($value) {
  return empty($value);
});

$tpl = <<<EOS
{{# jobs | empty }}
    No jobs!
{{/ jobs }}
{{^ jobs | empty }}
    <ul>
        {{# jobs }}
            <li>{{ title }}</li>
        {{/ jobs }}
    </ul>
{{/ jobs }}
EOS;

echo $m->render($tpl, [
  'jobs' => [],
]);
```

**Comment by tedhenry100** [comment]
Thank you! Both the jobs_count and filter options both work with my regular PHP array.
